spring:
  application:
    name: event-service-ticket241
  datasource:
    url: jdbc:postgresql://localhost:5432/event_service_db
    username: postgres
    password: azerty
    driver-class-name: org.postgresql.Driver
  jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true
          dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 9001
eureka:
  client:
    service-url:
      defaultZone:
        http://localhost:8781/eureka/


