spring:
  application:
    name: event-service-ticket241
  kafka:
    enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/event_service_db
    username: postgres
    password: azerty
    driver-class-name: org.postgresql.Driver
  jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true
          dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 9001
eureka:
  client:
    service-url:
      defaultZone:
        http://localhost:8781/eureka/


kafka:
  bootstrap-servers: localhost:9092

  # Configuration Producer
  producer:
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    properties:
      spring.json.add.type.headers: false
    acks: all
    retries: 3

  # Configuration Consumer
  consumer:
    group-id: event-service-group
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    properties:
      spring.json.trusted.packages: "*"
      spring.json.type.mapping: >
        TicketReservedEvent:com.tchelo.event_service_ticket241.kafka.event.TicketReservedEvent,
        TicketCancelledEvent:com.tchelo.event_service_ticket241.kafka.event.TicketCancelledEvent,
        ReservationExpiredEvent:com.tchelo.event_service_ticket241.kafka.event.ReservationExpiredEvent
    auto-offset-reset: earliest
    enable-auto-commit: false

  # Configuration Listener
  listener:
    ack-mode: manual